"""Se agrega relacion entre User y knowledge_sections

Revision ID: 728a5ffb64ac
Revises: 84ce92f3d799
Create Date: 2025-09-24 23:33:38.369346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728a5ffb64ac'
down_revision: Union[str, None] = '84ce92f3d799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
