"""Se agrega nuevo campo en knowledge_sections  que es user_id

Revision ID: 84ce92f3d799
Revises: d3ce530bd16a
Create Date: 2025-09-24 23:30:31.466291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ce92f3d799'
down_revision: Union[str, None] = 'd3ce530bd16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_sections', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'knowledge_sections', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_sections', type_='foreignkey')
    op.drop_column('knowledge_sections', 'user_id')
    # ### end Alembic commands ###
