"""update

Revision ID: 93eef812b5c1
Revises: 728a5ffb64ac
Create Date: 2025-09-25 23:09:29.852249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93eef812b5c1'
down_revision: Union[str, None] = '728a5ffb64ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###
